### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by ictsolved** [persona-id/persona-android-sdk#105]
I just replaced the template id with the sandbox ID of `Government ID + Selfie` from my account, but it is giving `Bad Request` in response. Template id from [documentation](https://docs.withpersona.com/docs/android-sdk-v2-integration-guide#build-and-launch-the-inquiry) works though.

**Comment by jacoblange-dev** [comment]
Hi it is tough for us to troubleshoot without a template id or inquiry id. Please reach out to support@withpersona.com and include an inquiry id to reach the proper channels. However, if you are using a sandbox only template please ensure you are passing `.environment(Environment.SANDBOX)` to the `InquiryTemplateBuilder` otherwise the request will fail.
